// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX1xhCf-e3hux5gr2XF63Fhzk5T4PwOIU',
    appId: '1:715913465217:web:1b6b4efcb23c27b2896c80',
    messagingSenderId: '715913465217',
    projectId: 'twitterclonetute-5dfc6',
    authDomain: 'twitterclonetute-5dfc6.firebaseapp.com',
    storageBucket: 'twitterclonetute-5dfc6.appspot.com',
    measurementId: 'G-V7YKF8MYBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3EDiT0zHzmsy1KJIql7wqvUSzFD0Znic',
    appId: '1:715913465217:android:4b1672015bf0c97f896c80',
    messagingSenderId: '715913465217',
    projectId: 'twitterclonetute-5dfc6',
    storageBucket: 'twitterclonetute-5dfc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1zqyT1XolQMvr443vjaHm8vYBSasi56E',
    appId: '1:715913465217:ios:db62206bd1860681896c80',
    messagingSenderId: '715913465217',
    projectId: 'twitterclonetute-5dfc6',
    storageBucket: 'twitterclonetute-5dfc6.appspot.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1zqyT1XolQMvr443vjaHm8vYBSasi56E',
    appId: '1:715913465217:ios:db62206bd1860681896c80',
    messagingSenderId: '715913465217',
    projectId: 'twitterclonetute-5dfc6',
    storageBucket: 'twitterclonetute-5dfc6.appspot.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX1xhCf-e3hux5gr2XF63Fhzk5T4PwOIU',
    appId: '1:715913465217:web:1979aa475d758164896c80',
    messagingSenderId: '715913465217',
    projectId: 'twitterclonetute-5dfc6',
    authDomain: 'twitterclonetute-5dfc6.firebaseapp.com',
    storageBucket: 'twitterclonetute-5dfc6.appspot.com',
    measurementId: 'G-47ERDSW7ZV',
  );
}
